name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  update-toc:
    name: Generator TOC and auto-commit
    runs-on: ubuntu-latest
    steps:
      - name: Install doctoc
        run: |
          sudo npm install -g doctoc
      - uses: actions/checkout@v2
      - name: Generate full TOC
        run: |
          doctoc --github --notitle readme.md
      - name: Commit changes
        run: git commit -a -m 'toc update'
      - name: Push changes
        run: git push
